In [1]:
import pandas as pd

# Đọc dữ liệu.
df = pd.read_csv('retail_sales_dataset_extended.csv')
df.head(5)

,Transaction ID,Date,Time,City,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Inventory,Import Cost,Promotion,Holiday
0,1,2023-11-24,10:40,TP.HCM,CUST001,Male,34,Beauty,3,50,150,79,32.62,No,No
1,2,2023-02-27,15:07,Hải Phòng,CUST002,Female,26,Clothing,2,500,1000,244,324.70,No,No
2,3,2023-01-13,19:01,TP.HCM,CUST003,Male,50,Electronics,1,30,30,47,23.44,Yes,No
3,4,2023-05-21,18:47,TP.HCM,CUST004,Male,37,Clothing,1,500,500,219,324.95,No,No
4,5,2023-05-06,18:17,Hà Nội,CUST005,Male,30,Beauty,2,50,100,115,32.72,No,No

In [2]:
# Kiểm tra thông tin.
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Time              1000 non-null   object
 3   City              1000 non-null   object
 4   Customer ID       1000 non-null   object
 5   Gender            1000 non-null   object
 6   Age               1000 non-null   int64
 7   Product Category  1000 non-null   object
 8   Quantity          1000 non-null   int64
 9   Price per Unit    1000 non-null   int64
 10  Total Amount      1000 non-null   int64
 11  Inventory         1000 non-null   int64
 12  Import Cost       1000 non-null   float64
 13  Promotion         1000 non-null   object
 14  Holiday           1000 non-null   object
dtypes: float64(1), int64(6), object(8)
memory usage: 117.3+ KB
None
Transaction ID      0
Date                0
Time                0
City                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
Inventory           0
Import Cost         0
Promotion           0
Holiday             0
dtype: int64

In [3]:
# Kiểm tra giá trị bất thường.
print('Kiểm tra Total Amount:')
df['Check_Total_Amount'] = df['Quantity'] * df['Price per Unit']
print('\n')
print(df[df['Check_Total_Amount'] != df['Total Amount']])

Kiểm tra Total Amount:


Empty DataFrame
Columns: [Transaction ID, Date, Time, City, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, Inventory, Import Cost, Promotion, Holiday, Check_Total_Amount]
Index: []

In [5]:
# Chuẩn hóa dữ liệu.
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df['Quarter'] = df['Date'].dt.quarter
df['Hour'] = pd.to_datetime(df['Time'], format='%H:%M').dt.hour

df.head(5)

,Transaction ID,Date,Time,City,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Inventory,Import Cost,Promotion,Holiday,Check_Total_Amount,Month,Quarter,Hour
0,1,2023-11-24,10:40,TP.HCM,CUST001,Male,34,Beauty,3,50,150,79,32.62,No,No,150,11,4,10
1,2,2023-02-27,15:07,Hải Phòng,CUST002,Female,26,Clothing,2,500,1000,244,324.70,No,No,1000,2,1,15
2,3,2023-01-13,19:01,TP.HCM,CUST003,Male,50,Electronics,1,30,30,47,23.44,Yes,No,30,1,1,19
3,4,2023-05-21,18:47,TP.HCM,CUST004,Male,37,Clothing,1,500,500,219,324.95,No,No,500,5,2,18
4,5,2023-05-06,18:17,Hà Nội,CUST005,Male,30,Beauty,2,50,100,115,32.72,No,No,100,5,2,18

In [10]:
# Phân nhóm tuổi.
bins = [18, 25, 35, 50, 100]
labels = ['18-25', '26-35', '36-50', '>50']
df['Age Group'] = pd.cut(df['Age'], bins=bins, labels=labels, right=True)

df.head(5)

,Transaction ID,Date,Time,City,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Inventory,Import Cost,Promotion,Holiday,Check_Total_Amount,Month,Quarter,Hour,Age Group
0,1,2023-11-24,10:40,TP.HCM,CUST001,Male,34,Beauty,3,50,150,79,32.62,No,No,150,11,4,10,26-35
1,2,2023-02-27,15:07,Hải Phòng,CUST002,Female,26,Clothing,2,500,1000,244,324.70,No,No,1000,2,1,15,26-35
2,3,2023-01-13,19:01,TP.HCM,CUST003,Male,50,Electronics,1,30,30,47,23.44,Yes,No,30,1,1,19,36-50
3,4,2023-05-21,18:47,TP.HCM,CUST004,Male,37,Clothing,1,500,500,219,324.95,No,No,500,5,2,18,36-50
4,5,2023-05-06,18:17,Hà Nội,CUST005,Male,30,Beauty,2,50,100,115,32.72,No,No,100,5,2,18,26-35

In [11]:
# Lưu dữ liệu đã được làm sạch.
df.to_csv('retail_sales_dataset_cleaned.csv', index=False)
print("Dữ liệu đã được làm sạch và lưu vào 'retail_sales_dataset_cleaned.csv'")

Dữ liệu đã được làm sạch và lưu vào 'retail_sales_dataset_cleaned.csv'